services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET_KEY=dea2bfed20dbae623b027b1b6688f400
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://user:password@mysql:3306/users_db
    depends_on:
      - mysql
    volumes:
      - ./backend:/app

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: users_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  mysql_data:
