"""Initial migration.

Revision ID: 179086f1c6dc
Revises: 7e70d88785f1
Create Date: 2024-07-06 08:29:07.633714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '179086f1c6dc'
down_revision = '7e70d88785f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=18),
               nullable=True)
        batch_op.alter_column('token',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=550),
               existing_nullable=True)
        batch_op.drop_index('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('phone', ['phone'], unique=True)
        batch_op.alter_column('token',
               existing_type=sa.String(length=550),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=18),
               type_=mysql.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
